Fix typo in fuse_plugin, calling the wrong repo method
The repo interface exposes the `get_client_generation_ids` method, but in
one location in `fuse_plugin` it is called as `get_clientgeneration_ids`.

As reported in Fedora bugzilla,
https://bugzilla.redhat.com/show_bug.cgi?id=1340138

    #1340138 [abrt] obnam: fuse_plugin.py:391:statfs:AttributeError: 'RepositoryFormat6' object has no attribute 'get_clientgeneration_ids'